### ISSUE TITLE
TODO: BitcartCC Long-term roadmap

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart#103]
This issue contains a list of long-term issues and features to add. We decided to switch to long-term planning instead of per-month planning.

## Core Daemons and Coins support

-  [ ] <strike>Omni layer support (electrum-omni probably)</strike>
- [ ] Ethereum support (#105)
- [x] Investigate weird issue failing CI at times (for example, [this CI run](https://app.circleci.com/pipelines/github/bitcartcc/bitcart/473/workflows/9713d18c-0cf0-42d8-8417-e1255bd72f36/jobs/1194))

## Merchants API

- [ ] Add ability to extend API endpoints and database schema with plugins
- [x] Refactor codebase (#109)

## Admin Panel
- [x] Add more server management settings to admin (lightning management?)
- [ ] Add ability to add new pages and extend navigation with plugins

## Store

- [ ] Add ability to extend store functionality or add new pages with plugins

## Docker and deployment

- [ ] Tor and using your own node support(bitcartcc/bitcart-docker#8)
- [ ] Add ability to add runtime plugins to API, store and admin

## Docs

- [x] Finalize docs

## BitCCL

- [ ] Add more functions and events for ease of usage
- [ ] Integrate into main Merchants API

## SDK

- [x] Release 1.0 (bitcartcc/bitcart-sdk#3)
- [x]  Refactor to stop using sync_generator.py (bitcartcc/bitcart-sdk#9)

## Other integrations and improvements
- [x] Set up release versioning (#125)

**Comment by MrNaif2018** [comment]
Closing in favour of https://github.com/orgs/bitcartcc/projects/1
