### ISSUE TITLE
TODO before setting up release versioning

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart#125]
Currently, when pushing a  commit to master, it is deployed automatically to docker hub at latest tag.
But when we add multiple architecture builds, it will not be desired to build everything on each commit.
Plus, having a clear changelog between versions will help people to notice the changes we do
Here's a list of issues we have to resolve before setting it all up:
- [x] 100 % test coverage on Merchants API (#122)
- [x] Upgrade all electrums to 4.0.3 (#123)
- [x] Release SDK 1.0 and use it (bitcartcc/bitcart-sdk#3)
- [x] Refactor some left code (#121)
- [x] Fix issue with balance fetching after wallet was added (#127)
- [x] Use APIManager for invoice status updates (#126)
- [x] Lower timeout on SDK poll_updates method (2->1 or less)
- [x] Fix scaling issues with postgres database connections (when cpu cores >= 4 and hyperthreading) (#134)
- [x] Decide on commit message guidelines (#118)
- [x] Check all code, that every component works
- [x] Check edge cases in invoice polling, for example, when there are no workers available (#126)
- [x] Maybe add a consistent payment request status mapping to daemon/SDK (already available as `status_str`)
- [x] Improve documentation, ensure it is up to date to everything currently added
- [x] Add changelog to SDK, and to other repos, finalize contributing guidelines

Then, we can start discussing versioning in bitcartcc.
