### ISSUE TITLE
Hacktoberfest welcome

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart#133]
This month [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is held!
We welcome all new and existing contributors, this issue is a list of all issues from bitcart projects(new features, bug fixes, etc.).
If you have any questions regarding the project, open an issue on github or contact us in our [Telegram group](https://t.me/bitcartcc).

- [x] TODO list of related issues before setting up release versioning (#125)
- [x] Fix all logos accross the platform (#129)
- [x] Set up logging (#141)
- [ ] Long-term list of issues (#103)
- [ ] bitcart-docker new features discussion (bitcartcc/bitcart-docker#8)
- [x] bitcart-store issue list (bitcartcc/bitcart-store#150)
- [x] bitcart-admin issue list (bitcartcc/bitcart-admin#10)

**Comment by MrNaif2018** [comment]
Thanks to everyone who has contributed to BitcartCC this hacktoberfest!
